name: "hello world workflow"

on:
    push:
        branches:
            - master
            - production

jobs:
    hello_world:
        runs-on: self-hosted
        steps:
            - name: print hello world
              run: echo "hello world"

